In [ ]:
import numpy as np

In [ ]:
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
a.shape

(5,)

In [ ]:
b=np.array([10.5,20.5,30.5])
print(b)

[10.5 20.5 30.5]


In [ ]:
b.dtype

dtype('float64')

In [ ]:
a.dtype

dtype('int64')

In [ ]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
c.ndim

2

In [ ]:
c.shape

(3, 3)

In [ ]:
c.dtype

dtype('int64')

In [ ]:
d=np.array([[10,20,30],[40,50,60]],dtype="float64")
print(d)

[[10. 20. 30.]
 [40. 50. 60.]]


In [ ]:
d1=np.array([[10,0,12,0,5],[34,80,0,0,8]],dtype=bool)
d1

array([[ True, False,  True, False,  True],
       [ True,  True, False, False,  True]])

In [ ]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [ ]:
f=np.ones((4,5))
f

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
f2=np.ones((4,5,2))
f2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
z1=np.zeros(5)
z2=np.zeros((4,5))
z3=np.zeros((2,4,5))
print(z1)
print(z2)
print(z3)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
aa=np.full((3,4),fill_value=25)
aa

array([[25, 25, 25, 25],
       [25, 25, 25, 25],
       [25, 25, 25, 25]])

In [ ]:
ab=np.arange(1,10)
ab

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ac=np.arange(1,21).reshape(2,10)
ac

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])